export enum align {
  align_baseline = 'align-baseline',
  align_top = 'align-top ',
  align_middle = 'align-middle',
  align_bottom = 'align-bottom',
  align_text_bottom = 'align-text-bottom',
  align_text_top = 'align-text-top'
}

export enum float {
  float_left = 'float-left',
  float_right = 'float-right',
  float_none = 'float-none',
  float_sm_left = 'float-sm-left',
  float_sm_right = 'float-sm-right',
  float_sm_none = 'float-sm-none',
  float_md_left = 'float-md-left',
  float_md_right = 'float-md-right',
  float_md_none = 'float-md-none',
  float_lg_left = 'float-lg-left',
  float_lg_right = 'float-lg-right',
  float_lg_none = 'float-lg-none',
  float_xl_left = 'float-xl-left',
  float_xl_right = 'float-xl-right',
  float_xl_none = 'float-xl-none'
}

export enum visibility {
  visible = 'visible',
  invisible = 'invisible'
}

export enum verticalAlign {
  align_baseline = 'align-baseline',
  align_top = 'align-top',
  align_middle = 'align-middle',
  align_bottom = 'align-bottom',
  align_text_bottom = 'align-text-bottom',
  align_text_top = 'align-text-top'
}

export enum sizing {
  w_25 = 'w-25',
  w_50 = 'w-50',
  mw_ = 'mw-',
  h_ = 'h-',
  mh_ = 'mh-'
}

export enum spacing {
  mt_ = 'mt-',
  mb_ = 'mb-',
  ml_ = 'ml-',
  mr_ = 'mr-',
  mx_ = 'mx-',
  my_ = 'my-',
  pt_ = 'pt-',
  pb_ = 'pb-',
  pl_ = 'pl-',
  pr_ = 'pr-',
  px_ = 'px-',
  py_ = 'py-'
}

export enum border {
  border = 'border',
  border_top = 'border-top',
  border_right = 'border-right',
  border_bottom = 'border-bottom',
  border_left = 'border-left',
  border_primary = 'border-primary',
  border_secondary = 'border-secondary',
  border_success = 'border-success',
  border_danger = 'border-danger',
  border_warning = 'border-warning',
  border_info = 'border-info',
  border_light = 'border-light',
  border_dark = 'border-dark',
  border_white = 'border-white',
  rounded = 'rounded',
  rounded_top = 'rounded-top',
  rounded_right = 'rounded-right',
  rounded_bottom = 'rounded-bottom',
  rounded_left = 'rounded-left',
  rounded_circle = 'rounded-circle',
  rounded_0 = 'rounded-0'
}

export enum colors {
  text_primary = 'text-primary',
  text_secondary = 'text-secondary',
  text_success = 'text-success',
  text_danger = 'text-danger',
  text_warning = 'text-warning',
  text_info = 'text-info',
  text_light = 'text-light',
  text_dark = 'text-dark',
  text_muted = 'text-muted',
  text_white = 'text-white',
  bg_primary = 'bg-primary',
  bg_secondary = 'bg-secondary',
  bg_success = 'bg-success',
  bg_danger = 'bg-danger',
  bg_warning = 'bg-warning',
  bg_info = 'bg-info',
  bg_light = 'bg-light',
  bg_dark = 'bg-dark',
  bg_white = 'bg-white',
  bg_gradient_primary = 'bg-gradient-primary',
  bg_gradient_secondary = 'bg-gradient-secondary',
  bg_gradient_success = 'bg-gradient-success',
  bg_gradient_danger = 'bg-gradient-danger',
  bg_gradient_warning = 'bg-gradient-warning',
  bg_gradient_info = 'bg-gradient-info',
  bg_gradient_light = 'bg-gradient-light',
  bg_gradient_dark = 'bg-gradient-dark',
  bg_gradient_white = 'bg-gradient-white'
}

export enum flex {
  d_flex = 'd-flex',
  d_inline_flex = 'd-inline-flex',
  d_sm_flex = 'd-sm-flex',
  d_sm_inline_flex = 'd-sm-inline-flex',
  d_md_flex = 'd-md-flex',
  d_md_inline_flex = 'd-md-inline-flex',
  d_lg_flex = 'd-lg-flex',
  d_lg_inline_flex = 'd-lg-inline-flex',
  d_xl_flex = 'd-xl-flex',
  d_xl_inline_flex = 'd-xl-inline-flex',
  flex_row = 'flex-row',
  flex_row_reverse = 'flex-row-reverse',
  flex_column = 'flex-column',
  flex_column_reverse = 'flex-column-reverse',
  flex_sm_row = 'flex-sm-row',
  flex_sm_row_reverse = 'flex-sm-row-reverse',
  flex_sm_column = 'flex-sm-column',
  flex_sm_column_reverse = 'flex-sm-column-reverse',
  flex_md_row = 'flex-md-row',
  flex_md_row_reverse = 'flex-md-row-reverse',
  flex_md_column = 'flex-md-column',
  flex_md_column_reverse = 'flex-md-column-reverse',
  flex_lg_row = 'flex-lg-row',
  flex_lg_row_reverse = 'flex-lg-row-reverse',
  flex_lg_column = 'flex-lg-column',
  flex_lg_column_reverse = 'flex-lg-column-reverse',
  flex_xl_row = 'flex-xl-row',
  flex_xl_row_reverse = 'flex-xl-row-reverse',
  flex_xl_column = 'flex-xl-column',
  flex_xl_column_reverse = 'flex-xl-column-reverse',
  justify_content_start = 'justify-content-start',
  justify_content_end = 'justify-content-end',
  justify_content_center = 'justify-content-center',
  justify_content_between = 'justify-content-between',
  justify_content_around = 'justify-content-around',
  justify_content_sm_start = 'justify-content-sm-start',
  justify_content_sm_end = 'justify-content-sm-end',
  justify_content_sm_center = 'justify-content-sm-center',
  justify_content_sm_between = 'justify-content-sm-between',
  justify_content_sm_around = 'justify-content-sm-around',
  justify_content_md_start = 'justify-content-md-start',
  justify_content_md_end = 'justify-content-md-end',
  justify_content_md_center = 'justify-content-md-center',
  justify_content_md_between = 'justify-content-md-between',
  justify_content_md_around = 'justify-content-md-around',
  justify_content_lg_start = 'justify-content-lg-start',
  justify_content_lg_end = 'justify-content-lg-end',
  justify_content_lg_center = 'justify-content-lg-center',
  justify_content_lg_between = 'justify-content-lg-between',
  justify_content_lg_around = 'justify-content-lg-around',
  justify_content_xl_start = 'justify-content-xl-start',
  justify_content_xl_end = 'justify-content-xl-end',
  justify_content_xl_center = 'justify-content-xl-center',
  justify_content_xl_between = 'justify-content-xl-between',
  justify_content_xl_around = 'justify-content-xl-around',
  align_items_start = 'align-items-start',
  align_items_end = 'align-items-end',
  align_items_center = 'align-items-center',
  align_items_baseline = 'align-items-baseline',
  align_items_stretch = 'align-items-stretch',
  align_items_sm_start = 'align-items-sm-start',
  align_items_sm_end = 'align-items-sm-end',
  align_items_sm_center = 'align-items-sm-center',
  align_items_sm_baseline = 'align-items-sm-baseline',
  align_items_sm_stretch = 'align-items-sm-stretch',
  align_items_md_start = 'align-items-md-start',
  align_items_md_end = 'align-items-md-end',
  align_items_md_center = 'align-items-md-center',
  align_items_md_baseline = 'align-items-md-baseline',
  align_items_md_stretch = 'align-items-md-stretch',
  align_items_lg_start = 'align-items-lg-start',
  align_items_lg_end = 'align-items-lg-end',
  align_items_lg_center = 'align-items-lg-center',
  align_items_lg_baseline = 'align-items-lg-baseline',
  align_items_lg_stretch = 'align-items-lg-stretch',
  align_items_xl_start = 'align-items-xl-start',
  align_items_xl_end = 'align-items-xl-end',
  align_items_xl_center = 'align-items-xl-center',
  align_items_xl_baseline = 'align-items-xl-baseline',
  align_items_xl_stretch = 'align-items-xl-stretch',
  align_self_start = 'align-self-start',
  align_self_end = 'align-self-end',
  align_self_center = 'align-self-center',
  align_self_baseline = 'align-self-baseline',
  align_self_stretch = 'align-self-stretch',
  align_self_sm_start = 'align-self-sm-start',
  align_self_sm_end = 'align-self-sm-end',
  align_self_sm_center = 'align-self-sm-center',
  align_self_sm_baseline = 'align-self-sm-baseline',
  align_self_sm_stretch = 'align-self-sm-stretch',
  align_self_md_start = 'align-self-md-start',
  align_self_md_end = 'align-self-md-end',
  align_self_md_center = 'align-self-md-center',
  align_self_md_baseline = 'align-self-md-baseline',
  align_self_md_stretch = 'align-self-md-stretch',
  align_self_lg_start = 'align-self-lg-start',
  align_self_lg_end = 'align-self-lg-end',
  align_self_lg_center = 'align-self-lg-center',
  align_self_lg_baseline = 'align-self-lg-baseline',
  align_self_lg_stretch = 'align-self-lg-stretch',
  align_self_xl_start = 'align-self-xl-start',
  align_self_xl_end = 'align-self-xl-end',
  align_self_xl_center = 'align-self-xl-center',
  align_self_xl_baseline = 'align-self-xl-baseline',
  align_self_xl_stretch = 'align-self-xl-stretch',
  flex_nowrap = 'flex-nowrap',
  flex_wrap = 'flex-wrap',
  flex_wrap_reverse = 'flex-wrap-reverse',
  flex_sm_nowrap = 'flex-sm-nowrap',
  flex_sm_wrap = 'flex-sm-wrap',
  flex_sm_wrap_reverse = 'flex-sm-wrap-reverse',
  flex_md_nowrap = 'flex-md-nowrap',
  flex_md_wrap = 'flex-md-wrap',
  flex_md_wrap_reverse = 'flex-md-wrap-reverse',
  flex_lg_nowrap = 'flex-lg-nowrap',
  flex_lg_wrap = 'flex-lg-wrap',
  flex_lg_wrap_reverse = 'flex-lg-wrap-reverse',
  flex_xl_nowrap = 'flex-xl-nowrap',
  flex_xl_wrap = 'flex-xl-wrap',
  flex_xl_wrap_reverse = 'flex-xl-wrap-reverse',
  order_0 = 'order-0',
  order_1 = 'order-1',
  order_2 = 'order-2',
  order_3 = 'order-3',
  order_4 = 'order-4',
  order_5 = 'order-5',
  order_6 = 'order-6',
  order_7 = 'order-7',
  order_8 = 'order-8',
  order_9 = 'order-9',
  order_10 = 'order-10',
  order_11 = 'order-11',
  order_12 = 'order-12'
}

export enum position {
  position_static = 'position-static',
  position_relative = 'position-relative',
  position_absolute = 'position-absolute',
  position_fixed = 'position-fixed',
  position_sticky = 'position-sticky',
  fixed_top = 'fixed-top',
  fixed_bottom = 'fixed-bottom',
  sticky_top = 'sticky-top'
}
