version: '3'
services:
  web:
    image: tristanteu/react-track
    container_name: "react-track"
    restart: "always"
    ports:
    - "3001:80"
    volumes:
    - ~/.timetracking-db:/root/.timetracking-db
    - ~/.timetracking-backup-db:/root/.timetracking-backup-db
