export enum LeaveErrorKeys {
  LEAVEDAY_START_DATE_AFTER_END_DATE = 'LEAVEDAY_START_DATE_AFTER_END_DATE',
  LEAVEDAY_DATES_IN_OTHER_YEAR = 'LEAVEDAY_DATES_IN_OTHER_YEAR',
  LEAVEDAY_TIMESTAMPS_ALREADY_EXIST = 'LEAVEDAY_TIMESTAMPS_ALREADY_EXIST',
  LEAVEDAY_ALREADY_EXISTS = 'LEAVEDAY_ALREADY_EXISTS',
  LEAVEDAY_MISSING_DAYS = 'LEAVEDAY_MISSING_DAYS'
}

export enum PauseErrorKeys {
  PAUSE_ALREADY_EXISTS = 'PAUSE_ALREADY_EXISTS'
}

export enum PublicHolidayErrorKeys {
  PUBLIC_HOLIDAY_ERROR = 'PUBLIC_HOLIDAY_ERROR'
}

export enum StatisticErrorKeys {
  STATISTIC_ERROR = 'STATISTIC_ERROR'
}

export enum TimestampsErrorKeys {
  INVALID_TIMESTAMPS = 'INVALID_TIMESTAMPS'
}

export enum ComplainsErrorKeys {}

export enum ComplainsErrorKeys {
  INVALID_COMPLAINS = 'INVALID_COMPLAINS'
}

export enum UserErrorKeys {
  INVALID_USER_PROPERTIES = 'INVALID_USER_PROPERTIES',
  INVALID_WORK_TIMES = 'INVALID_WORK_TIMES',
  CODE_ALREADY_IN_USE = 'CODE_ALREADY_IN_USE',
  MISSING_USER_ID = 'MISSING_USER_ID',
  NO_USER_FOR_CODE = 'NO_USER_FOR_CODE',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  INVALID_ROLE = 'INVALID_ROLE',
  INVALID_SALDOS = 'INVALID_SALDOS'
}

export enum ScannedUserErrorKeys {}

export enum LicenseErrorKeys {
  LICENSE_NOT_FOUND = 'LICENSE_NOT_FOUND'
}
