export const beepSound = new Audio(
  'data:audio/wav;base64,' +
    '//uQRAAAAWMSLwUIYAAsYkXgoQwAEaYLWfkWgAI0wWs/' +
    'ItAAAGDgYtAgAyN+QWaAAihwMWm4G8QQRDiMcCBcH3Cc' +
    '+CDv/7xA4Tvh9Rz/y8QADBwMWgQAZG/ILNAARQ4GLTcD' +
    'eIIIhxGOBAuD7hOfBB3/94gcJ3w+o5/5eIAIAAAVwWgQ' +
    'AVQ2ORaIQwEMAJiDg95G4nQL7mQVWI6GwRcfsZAcsKkJ' +
    'vxgxEjzFUgfHoSQ9Qq7KNwqHwuB13MA4a1q/DmBrHgPc' +
    'mjiGoh//EwC5nGPEmS4RcfkVKOhJf+WOgoxJclFz3kgn' +
    '//dBA+ya1GhurNn8zb//9NNutNuhz31f////9vt///z+' +
    'IdAEAAAK4LQIAKobHItEIYCGAExBwe8jcToF9zIKrEdD' +
    'YIuP2MgOWFSE34wYiR5iqQPj0JIeoVdlG4VD4XA67mAc' +
    'Na1fhzA1jwHuTRxDUQ//iYBczjHiTJcIuPyKlHQkv/LH' +
    'QUYkuSi57yQT//uggfZNajQ3Vmz+Zt//+mm3Wm3Q576v' +
    '////+32///5/EOgAAADVghQAAAAA//uQZAUAB1WI0PZu' +
    'gAAAAAoQwAAAEk3nRd2qAAAAACiDgAAAAAAABCqEEQRL' +
    'CgwpBGMlJkIz8jKhGvj4k6jzRnqasNKIeoh5gI7BJaC1' +
    'A1AoNBjJgbyApVS4IDlZgDU5WUAxEKDNmmALHzZp0Fkz' +
    '1FMTmGFl1FMEyodIavcCAUHDWrKAIA4aa2oCgILEBupZ' +
    'gHvAhEBcZ6joQBxS76AgccrFlczBvKLC0QI2cBoCFvfT' +
    'DAo7eoOQInqDPBtvrDEZBNYN5xwNwxQRfw8ZQ5wQVLvO' +
    '8OYU+mHvFLlDh05Mdg7BT6YrRPpCBznMB2r//xKJjyyO' +
    'h+cImr2/4doscwD6neZjuZR4AgAABYAAAABy1xcdQtxY' +
    'BYYZdifkUDgzzXaXn98Z0oi9ILU5mBjFANmRwlVJ3/6j' +
    'YDAmxaiDG3/6xjQQCCKkRb/6kg/wW+kSJ5//rLobkLSi' +
    'KmqP/0ikJuDaSaSf/6JiLYLEYnW/+kXg1WRVJL/9EmQ1' +
    'YZIsv/6Qzwy5qk7/+tEU0nkls3/zIUMPKNX/6yZLf+kF' +
    'gAfgGyLFAUwY//uQZAUABcd5UiNPVXAAAApAAAAAE0VZ' +
    'QKw9ISAAACgAAAAAVQIygIElVrFkBS+Jhi+EAuu+lKAk' +
    'YUEIsmEAEoMeDmCETMvfSHTGkF5RWH7kz/ESHWPAq/kc' +
    'CRhqBtMdokPdM7vil7RG98A2sc7zO6ZvTdM7pmOUAZTn' +
    'JW+NXxqmd41dqJ6mLTXxrPpnV8avaIf5SvL7pndPvPpn' +
    'dJR9Kuu8fePvuiuhorgWjp7Mf/PRjxcFCPDkW31srioC' +
    'Exivv9lcwKEaHsf/7ow2Fl1T/9RkXgEhYElAoCLFtMAr' +
    'xwivDJJ+bR1HTKJdlEoTELCIqgEwVGSQ+hIm0NbK8WXc' +
    'TEI0UPoa2NbG4y2K00JEWbZavJXkYaqo9CRHS55FcZTj' +
    'KEk3NKoCYUnSQ0rWxrZbFKbKIhOKPZe1cJKzZSaQrIyU' +
    'LHDZmV5K4xySsDRKWOruanGtjLJXFEmwaIbDLX0hIPBU' +
    'QPVFVkQkDoUNfSoDgQGKPekoxeGzA4DUvnn4bxzcZrtJ' +
    'yipKfPNy5w+9lnXwgqsiyHNeSVpemw4bWb9psYeq//uQ' +
    'ZBoABQt4yMVxYAIAAAkQoAAAHvYpL5m6AAgAACXDAAAA' +
    'D59jblTirQe9upFsmZbpMudy7Lz1X1DYsxOOSWpfPqNX' +
    '2WqktK0DMvuGwlbNj44TleLPQ+Gsfb+GOWOKJoIrWb3c' +
    'IMeeON6lz2umTqMXV8Mj30yWPpjoSa9ujK8SyeJP5y5m' +
    'OW1D6hvLepeveEAEDo0mgCRClOEgANv3B9a6fikgUSu/' +
    'DmAMATrGx7nng5p5iimPNZsfQLYB2sDLIkzRKZOHGAaU' +
    'yDcpFBSLG9MCQALgAIgQs2YunOszLSAyQYPVC2YdGGeH' +
    'D2dTdJk1pAHGAWDjnkcLKFymS3RQZTInzySoBwMG0Que' +
    'C3gMsCEYxUqlrcxK6k1LQQcsmyYeQPdC2YfuGPASCBkc' +
    'VMQQqpVJshui1tkXQJQV0OXGAZMXSOEEBRirXbVRQW7u' +
    'gq7IM7rPWSZyDlM3IuNEkxzCOJ0ny2ThNkyRai1b6ev/' +
    '/3dzNGzNb//4uAvHT5sURcZCFcuKLhOFs8mLAAEAt4UW' +
    'AAIABAAAAAB4qbHo0tIjVkUU//uQZAwABfSFz3ZqQAAA' +
    'AAngwAAAE1HjMp2qAAAAACZDgAAAD5UkTE1UgZEUExqY' +
    'ynN1qZvqIOREEFmBcJQkwdxiFtw0qEOkGYfRDifBui9M' +
    'Qg4QAHAqWtAWHoCxu1Yf4VfWLPIM2mHDFsbQEVGwyqQo' +
    'QcwnfHeIkNt9YnkiaS1oizycqJrx4KOQjahZxWbcZgzt' +
    'j2c49nKmkId44S71j0c8eV9yDK6uPRzx5X18eDvjvQ6y' +
    'Ko9ZSS6l//8elePK/Lf//IInrOF/FvDoADYAGBMGb7Ft' +
    'Erm5MXMlmPAJQVgWta7Zx2go+8xJ0UiCb8LHHdftWyLJ' +
    'E0QIAIsI+UbXu67dZMjmgDGCGl1H+vpF4NSDckSIkk7V' +
    'd+sxEhBQMRU8j/12UIRhzSaUdQ+rQU5kGeFxm+hb1oh6' +
    'pWWmv3uvmReDl0UnvtapVaIzo1jZbf/pD6ElLqSX+rUm' +
    'OQNpJFa/r+sa4e/pBlAABoAAAAA3CUgShLdGIxsY7AUA' +
    'BPRrgCABdDuQ5GC7DqPQCgbbJUAoRSUj+NIEig0YfyWU' +
    'ho1VBBBA//uQZB4ABZx5zfMakeAAAAmwAAAAF5F3P0w9' +
    'GtAAACfAAAAAwLhMDmAYWMgVEG1U0FIGCBgXBXAtfMH1' +
    '0000EEEEEECUBYln03TTTdNBDZopopYvrTTdNa325mIm' +
    'Ng3TTPV9q3pmY0xoO6bv3r00y+IDGid/9aaaZTGMuj9m' +
    'pu9Mpio1dXrr5HERTZSmqU36A3CumzN/9Robv/Xx4v9i' +
    'jkSRSNLQhAWumap82WRSBUqXStV/YcS+XVLnSS+WLDro' +
    'qArFkMEsAS+eWmrUzrO0oEmE40RlMZ5+ODIkAyKAGUwZ' +
    '3mVKmcamcJnMW26MRPgUw6j+LkhyHGVGYjSUUKNpuJUQ' +
    'oOIAyDvEyG8S5yfK6dhZc0Tx1KI/gviKL6qvvFs1+bWt' +
    'az58uUNnryq6kt5RzOCkPWlVqVX2a/EEBUdU1KrXLf40' +
    'GoiiFXK///qpoiDXrOgqDR38JB0bw7SoL+ZB9o1RCkQj' +
    'Q2CBYZKd/+VJxZRRZlqSkKiws0WFxUyCwsKiMy7hUVFh' +
    'IaCrNQsKkTIsLivwKKigsj8XYlwt/WKi2N4d//uQRCSA' +
    'AjURNIHpMZBGYiaQPSYyAAABLAAAAAAAACWAAAAApUF/' +
    'Mg+0aohSIRobBAsMlO//Kk4soosy1JSFRYWaLC4qZBYW' +
    'FRGZdwqKiwkNBVmoWFSJkWFxX4FFRQWR+LsS4W/rFRb/' +
    '////////////////////////////////////////////' +
    '////////////////////////////////////////////' +
    '////////////////////////////////////////////' +
    '////////////////////////////////////////////' +
    '////////////////////////////////////////////' +
    '////////////////////////////////////////////' +
    '////////////////////////////////////////////' +
    '////////////////////////////////////////////' +
    '////////////////////////////////////////////' +
    '////////////////////VEFHAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAU291bmRib3kuZGUAAAAAAAAA' +
    'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
    'AAAAAAAAAAAAMjAwNGh0dHA6Ly93d3cuc291bmRib3ku' +
    'ZGUAAAAAAAAAACU='
);
